services:
  app:
    build: ./backend
    container_name: telecare_app
    ports:
      - "4001:4001"
    environment:
      NODE_ENV: production
      PORT: 4001
      DB_HOST: db
      DB_PORT: 5432
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
    env_file:
      - .env
    depends_on:
      - db
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    container_name: telecare_mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  db:
    image: postgres:16-alpine
    container_name: telecare_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
